[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=80", "wheel" ]

[project]
name = "xpsh"
version = "0.3.0"
description = "Expense sharing tool."
readme = "README.md"
license-files = [ "LICENSE" ]
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "click>=8.4",
  "filelock>=3.29",
  "rich>=15",
  "streamlit>=1.57",
]
urls.Repository = "https://github.com/mmarinriera/xpsh"
scripts.xpsh = "xpsh.scripts.main:xpsh"

[dependency-groups]
dev = [
  "coverage[toml]>=7.13.4",
  "pytest>=9",
  "pytest-lazy-fixtures>=1.4",
]

[tool.setuptools]
packages.find.where = [ "src" ]
include-package-data = true

[tool.uv]
required-version = ">=0.11.0"

[tool.ruff]
target-version = "py313"
line-length = 120
fix-only = true
lint.select = [ "ALL" ]
lint.ignore = [ "COM812", "D203", "D212" ]
lint.isort.force-single-line = true

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.pytest]
minversion = "9.0"
addopts = [ "-s", "-vvv" ]
testpaths = [
  "tests",
]
log_cli = true
log_cli_level = "DEBUG"

[tool.coverage]
run.branch = true
run.source = [ "xpsh" ]
# Regexes for lines to exclude from consideration
report.exclude_also = [
  # Don't complain about abstract methods, they aren't run:
  "@(abc\\.)?abstractmethod",
  # Don't complain about missing debug-only code:
  "def __repr__",
  "if __name__ == .__main__.:",
  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if self\\.debug",
  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",
]
report.ignore_errors = true
html.directory = ".coverage_html_report"

[tool.semantic_release]
build_command = """
    uv lock --upgrade-package "$PACKAGE_NAME"
    git add uv.lock
    uv build
"""
version_toml = [ "pyproject.toml:project.version" ]
branch = "main"
commit_message = "chore(release): version {version}"
allow_zero_version = true
changelog.default_templates.changelog_file = "CHANGELOG.md"
publish.upload_to_vcs_release = false
